---
title: "Regression models Project"
output:
  html_document: default
---

```{r}
summary(mtcars)
str(mtcars)

fit <- lm(mpg~factor(am),data=mtcars)
summary(fit)
plot(fit)

pairs(mtcars, main = "mtcars data")
cor(mtcars)

library(car)
scatterplotMatrix(mtcars,  main="Scatterplot Matrix")
crPlots(fit)

fit2 <- lm(mpg~.,data=mtcars)
avPlots(fit2)
summary(fit2)
plot(fit2)
crPlots(fit2)
with(mtcars,plot(disp,mpg))
with(mtcars,plot(disp,1/mpg))

library(datasets)
fit3 <- lm(mpg~wt+qsec+am+hp+disp,data=mtcars[-c(9,31),])
summary(fit3)
par(mfrow=c(2,2))
dfbetas(fit3)
which((hatvalues(fit3))>0.4)
plot(fit3)
library(car)
vif(fit3)
summary(powerTransform(mtcars$disp))
boxTidwell(mpg~wt+qsec+am+hp+disp,data=mtcars[-c(9,31),])

fit5 <- lm(I(1/mpg)~wt+I(hp/wt)+am,data=mtcars)
par(mfrow=c(1,1))
plot(fit5)
summary(fit5)

#重量、排量、档位
fit6 <- lm(mpg~wt+disp+am,data=mtcars)
plot(fit6)
summary(fit6)

#mpg倒数
fit7 <- lm(I(1/mpg)~wt+I(hp/wt),data=mtcars)
par(mfrow=c(2,2))
plot(fit7)
summary(fit7)

```

We will now use the package `leaps` to evaluate all the best-subset models.
```{r}
library(leaps)
regfit.full=regsubsets(mpg~.,data=mtcars)
summary(regfit.full)
```
It gives by default best-subsets up to size 8; lets increase that to 19, i.e. all the variables
```{r}
regfit.full=regsubsets(mpg~.,data=mtcars, nvmax=10)
reg.summary=summary(regfit.full)
names(reg.summary)
plot(reg.summary$bic,xlab="Number of Variables",ylab="Cp")
which.min(reg.summary$adjr2)
points(10,reg.summary$cp[10],pch=20,col="red")
```
There is a plot method for the `regsubsets`  object
```{r}
plot(regfit.full,scale="Cp")
coef(regfit.full,10)
```


